/**
 * themes.js — 15 preset slide themes (fonts + palette + background).
 *
 * Each theme object:
 *   id           unique key, also maps to reveal.js theme name when possible
 *   label        display name
 *   revealTheme  reveal.js CSS theme (may differ from id)
 *   headingFont  CSS font-family for slide titles
 *   bodyFont     CSS font-family for slide body
 *   primary      hex — button / accent
 *   secondary    hex — secondary accent
 *   accent       hex — highlight / link
 *   background   hex — slide background
 *   surface      hex — text-bearing surface (card inside slide)
 *   text         hex — primary text
 *   textMuted    hex — secondary text
 *   dark         boolean — dark bg?
 */
export const PRESET_THEMES = [
  {
    id: 'obsidian',
    label: 'Obsidian',
    revealTheme: 'black',
    headingFont: '"Inter", sans-serif',
    bodyFont: '"Inter", sans-serif',
    primary: '#7c6af7',
    secondary: '#a78bfa',
    accent: '#38bdf8',
    background: '#0f0f11',
    surface: '#1a1a22',
    text: '#f1f0ff',
    textMuted: '#9191a8',
    dark: true,
  },
  {
    id: 'slate',
    label: 'Slate Night',
    revealTheme: 'night',
    headingFont: '"Sora", sans-serif',
    bodyFont: '"Sora", sans-serif',
    primary: '#4ade80',
    secondary: '#86efac',
    accent: '#22d3ee',
    background: '#0d1117',
    surface: '#161b22',
    text: '#e6edf3',
    textMuted: '#8b949e',
    dark: true,
  },
  {
    id: 'dracula',
    label: 'Dracula',
    revealTheme: 'dracula',
    headingFont: '"Fira Code", monospace',
    bodyFont: '"Fira Code", monospace',
    primary: '#bd93f9',
    secondary: '#ff79c6',
    accent: '#50fa7b',
    background: '#282a36',
    surface: '#343746',
    text: '#f8f8f2',
    textMuted: '#6272a4',
    dark: true,
  },
  {
    id: 'moon',
    label: 'Moon',
    revealTheme: 'moon',
    headingFont: '"Palatino Linotype", serif',
    bodyFont: '"Palatino Linotype", serif',
    primary: '#93c5fd',
    secondary: '#bfdbfe',
    accent: '#fcd34d',
    background: '#002b36',
    surface: '#073642',
    text: '#aab2bc',
    textMuted: '#657b83',
    dark: true,
  },
  {
    id: 'league',
    label: 'League',
    revealTheme: 'league',
    headingFont: '"League Gothic", Impact, sans-serif',
    bodyFont: '"Lato", sans-serif',
    primary: '#f0be4b',
    secondary: '#e5c07b',
    accent: '#c792ea',
    background: '#1c1e20',
    surface: '#262728',
    text: '#eeeeee',
    textMuted: '#888888',
    dark: true,
  },
  {
    id: 'snow',
    label: 'Snow',
    revealTheme: 'white',
    headingFont: '"Helvetica Neue", Helvetica, sans-serif',
    bodyFont: '"Helvetica Neue", Helvetica, sans-serif',
    primary: '#2563eb',
    secondary: '#3b82f6',
    accent: '#0891b2',
    background: '#ffffff',
    surface: '#f8fafc',
    text: '#0f172a',
    textMuted: '#64748b',
    dark: false,
  },
  {
    id: 'sky',
    label: 'Sky',
    revealTheme: 'sky',
    headingFont: '"Open Sans", sans-serif',
    bodyFont: '"Open Sans", sans-serif',
    primary: '#2563eb',
    secondary: '#0284c7',
    accent: '#0e7490',
    background: '#dbeafe',
    surface: '#eff6ff',
    text: '#1e3a5f',
    textMuted: '#3b82f6',
    dark: false,
  },
  {
    id: 'parchment',
    label: 'Parchment',
    revealTheme: 'beige',
    headingFont: '"Palatino Linotype", serif',
    bodyFont: '"Georgia", serif',
    primary: '#92400e',
    secondary: '#b45309',
    accent: '#78350f',
    background: '#fef9c3',
    surface: '#fefce8',
    text: '#44371a',
    textMuted: '#78716c',
    dark: false,
  },
  {
    id: 'solarized',
    label: 'Solarized',
    revealTheme: 'solarized',
    headingFont: '"Gill Sans", sans-serif',
    bodyFont: '"Gill Sans", sans-serif',
    primary: '#268bd2',
    secondary: '#2aa198',
    accent: '#d33682',
    background: '#fdf6e3',
    surface: '#eee8d5',
    text: '#657b83',
    textMuted: '#93a1a1',
    dark: false,
  },
  {
    id: 'serif-warm',
    label: 'Serif Warm',
    revealTheme: 'serif',
    headingFont: '"Cambria", "Times New Roman", serif',
    bodyFont: '"Cambria", "Times New Roman", serif',
    primary: '#7c3aed',
    secondary: '#a855f7',
    accent: '#c026d3',
    background: '#f5ebe0',
    surface: '#fdf8f0',
    text: '#3b2f2f',
    textMuted: '#7c6f6f',
    dark: false,
  },
  {
    id: 'rose',
    label: 'Rose Dawn',
    revealTheme: 'simple',
    headingFont: '"Playfair Display", serif',
    bodyFont: '"Source Sans Pro", sans-serif',
    primary: '#e11d48',
    secondary: '#fb7185',
    accent: '#f43f5e',
    background: '#fff1f2',
    surface: '#fff5f5',
    text: '#881337',
    textMuted: '#9f1239',
    dark: false,
  },
  {
    id: 'forest',
    label: 'Forest',
    revealTheme: 'simple',
    headingFont: '"Merriweather", serif',
    bodyFont: '"Source Sans Pro", sans-serif',
    primary: '#16a34a',
    secondary: '#22c55e',
    accent: '#4ade80',
    background: '#052e16',
    surface: '#064e3b',
    text: '#d1fae5',
    textMuted: '#6ee7b7',
    dark: true,
  },
  {
    id: 'corporate',
    label: 'Corporate',
    revealTheme: 'simple',
    headingFont: '"Roboto", sans-serif',
    bodyFont: '"Roboto", sans-serif',
    primary: '#1d4ed8',
    secondary: '#1e40af',
    accent: '#0369a1',
    background: '#f0f4ff',
    surface: '#ffffff',
    text: '#1e293b',
    textMuted: '#475569',
    dark: false,
  },
  {
    id: 'retro',
    label: 'Retro',
    revealTheme: 'simple',
    headingFont: '"Space Grotesk", sans-serif',
    bodyFont: '"Space Grotesk", sans-serif',
    primary: '#f97316',
    secondary: '#fb923c',
    accent: '#fbbf24',
    background: '#1a0a00',
    surface: '#2d1700',
    text: '#fde8c8',
    textMuted: '#c4a882',
    dark: true,
  },
  {
    id: 'minimal',
    label: 'Minimal',
    revealTheme: 'simple',
    headingFont: '"DM Sans", sans-serif',
    bodyFont: '"DM Sans", sans-serif',
    primary: '#18181b',
    secondary: '#3f3f46',
    accent: '#71717a',
    background: '#fafafa',
    surface: '#ffffff',
    text: '#09090b',
    textMuted: '#71717a',
    dark: false,
  },
]

export const DEFAULT_THEME_ID = 'obsidian'

/** Look up a theme by id. Falls back to the default. */
export function getTheme(id) {
  return PRESET_THEMES.find((t) => t.id === id) || PRESET_THEMES[0]
}

/** The master-slide layouts per deck. Each deck can have 1–3 masters. */
export const MASTER_LAYOUTS = [
  {
    id: 'title',
    label: 'Title Master',
    titleY: '38%',
    titleAlign: 'center',
    bodyY: '62%',
    bodyAlign: 'center',
    showLogo: true,
    footerText: '',
  },
  {
    id: 'content',
    label: 'Content Master',
    titleY: '8%',
    titleAlign: 'left',
    bodyY: '25%',
    bodyAlign: 'left',
    showLogo: false,
    footerText: '',
  },
  {
    id: 'section',
    label: 'Section Master',
    titleY: '45%',
    titleAlign: 'center',
    bodyY: '70%',
    bodyAlign: 'center',
    showLogo: false,
    footerText: '',
  },
]

/** Pre-built deck templates (seed content). */
export const DECK_TEMPLATES = [
  {
    id: 'pitch',
    label: 'Pitch Deck',
    description: 'Startup pitch: problem, solution, traction, ask.',
    themeId: 'obsidian',
    slides: [
      { title: 'Company Name', content: '<p style="text-align:center">Tagline goes here</p>', notes: 'Introduce yourself and the company.', background: '', master: 'title' },
      { title: 'The Problem', content: '<ul><li>Pain point 1</li><li>Pain point 2</li><li>Pain point 3</li></ul>', notes: 'Make the audience feel the pain.', background: '', master: 'content' },
      { title: 'Our Solution', content: '<p>Clear, concise description of what you build.</p>', notes: 'Show a screenshot or demo.', background: '', master: 'content' },
      { title: 'Traction', content: '<p><strong>$X ARR</strong> · <strong>N customers</strong> · MoM growth</p>', notes: 'Use real numbers.', background: '', master: 'content' },
      { title: 'The Ask', content: '<p>Raising <strong>$XM Seed</strong> at a $YM pre-money.</p>', notes: 'Be direct.', background: '', master: 'content' },
    ],
  },
  {
    id: 'project-plan',
    label: 'Project Plan',
    description: 'Roadmap, milestones, and team overview.',
    themeId: 'corporate',
    slides: [
      { title: 'Project Name', content: '<p style="text-align:center">Q3 2026 · Owner: Your Name</p>', notes: '', background: '', master: 'title' },
      { title: 'Objectives', content: '<ul><li>Goal 1</li><li>Goal 2</li><li>Goal 3</li></ul>', notes: 'Link to OKRs.', background: '', master: 'content' },
      { title: 'Milestones', content: '<ul><li><strong>Month 1</strong> – Phase A complete</li><li><strong>Month 2</strong> – Phase B complete</li><li><strong>Month 3</strong> – Launch</li></ul>', notes: '', background: '', master: 'content' },
      { title: 'Risks', content: '<ul><li>Risk 1 – mitigation</li><li>Risk 2 – mitigation</li></ul>', notes: '', background: '', master: 'content' },
    ],
  },
  {
    id: 'lesson-plan',
    label: 'Lesson Plan',
    description: 'Classroom-ready slides for a single lesson.',
    themeId: 'sky',
    slides: [
      { title: 'Lesson Title', content: '<p style="text-align:center">Subject · Grade · Date</p>', notes: '', background: '', master: 'title' },
      { title: 'Learning Objectives', content: '<ul><li>By end of class, students will…</li><li>Objective 2</li></ul>', notes: '', background: '', master: 'content' },
      { title: 'Introduction', content: '<p>Hook or warm-up activity</p>', notes: 'Allow 5 min.', background: '', master: 'content' },
      { title: 'Main Content', content: '<p>Core concept explained</p>', notes: '', background: '', master: 'content' },
      { title: 'Activity', content: '<p>Student exercise description</p>', notes: 'Monitor groups.', background: '', master: 'content' },
      { title: 'Recap & Homework', content: '<ul><li>Key takeaways</li><li>Homework assignment</li></ul>', notes: '', background: '', master: 'content' },
    ],
  },
  {
    id: 'quarterly-review',
    label: 'Quarterly Review',
    description: 'Q-over-Q metrics, wins, blockers, next quarter plan.',
    themeId: 'slate',
    slides: [
      { title: 'Q? Review', content: '<p style="text-align:center">Team Name · Date</p>', notes: '', background: '', master: 'title' },
      { title: 'Metrics', content: '<ul><li>Metric A: X vs target Y</li><li>Metric B: X vs target Y</li></ul>', notes: 'Pull from dashboard.', background: '', master: 'content' },
      { title: 'Wins', content: '<ul><li>Win 1</li><li>Win 2</li></ul>', notes: '', background: '', master: 'content' },
      { title: 'Blockers', content: '<ul><li>Blocker 1 – owner</li><li>Blocker 2 – owner</li></ul>', notes: '', background: '', master: 'content' },
      { title: 'Next Quarter', content: '<ul><li>Priority 1</li><li>Priority 2</li><li>Priority 3</li></ul>', notes: '', background: '', master: 'content' },
    ],
  },
]
